version: '3.3'
services:
  mysqlservice:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  productService:
    image: productimage
    build: ProductMongo/
    restart: always
    hostname: localhost
    network_mode: host
    depends_on:
      - mongo
    ports:
      - 8073:8073


  mongo:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    container_name: mongo
    network_mode: host

  authenticservice:
    container_name: user_authentication_service
    build: authenticationservice/
    hostname: localhost
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mysqlservice
    restart: always

  cloudapiservce:
    image: johnson1887/cloud-api-service
    build: APIGatewayService/
    restart: always
    network_mode: host
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
